#!/usr/bin/env python3
"""
Write THIRD-PARTY-NOTICES.md from what the images are pinned to.

    python tools/third_party_notices.py            # write it
    python tools/third_party_notices.py --check     # exit 1 if it is stale

A release ships other people's code, and most of their licences ask for the
notice to travel with it. Keeping that list by hand means keeping it wrong:
a dependency is added in one line and the notice is somebody else's problem
three months later.

Names AND versions come from `tests/test_dependency_licences._pins()` —
requirements.txt plus the Dockerfile's own `pip install`, which is where
Playwright is pinned for the browser image. One source, so the notices and
the licence rule cannot disagree about what ships.

Why not installed metadata, which is where the version used to come from:
because then the file describes the machine it was generated on. The first
CI run this repository ever had proved it. The `suite` job installs
requirements.txt and not Playwright — which only the browser stage needs —
so regenerating there produced an entry reading "Not installed in the
environment this was generated from" where the committed file said
"playwright 1.62.0", and `tests/test_release_files.py` compares the two byte
for byte. The test could pass in exactly two places: this laptop, and the
one job that installs a browser.

Every line of requirements.txt is an exact `==`, so the pin IS the installed
version; reading it from the environment bought nothing and cost this.

The licence TEXT still needs an installed wheel — nothing else has it. So an
entry whose package is absent keeps the text already in the file, provided
the version it was written for is the version pinned now. That makes
regeneration idempotent anywhere, which is the property the test needs. A
version that has MOVED under an absent package is not carried over: the
licence of 2.0 is not evidence about 3.0, and the entry says plainly that it
has to be regenerated somewhere the package is installed.

No new dependency. `importlib.metadata` is the standard library, and the
licence text is whatever the wheel put in its `dist-info`.
"""

import argparse
import importlib.metadata as metadata
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

OUTPUT = os.path.join(ROOT, "THIRD-PARTY-NOTICES.md")

HEADER = """# Third-party notices

WDash is MIT licensed. It ships other people's work, and this file is that
work: every runtime dependency of the published images, the version pinned,
the licence it is under, and the licence text where the package carries one.

Generated by `tools/third_party_notices.py` from what `requirements.txt`
pins and what the Dockerfile installs — not a list kept by hand, and not a
description of whichever machine last ran it. `tests/test_release_files.py`
fails if it is stale, and `RELEASING.md` names the command.

Nothing here is proprietary or source-available; that rule is enforced
separately, by `tests/test_dependency_licences.py`. Two are LGPL v3 —
`ldap3` and `psycopg` — used as libraries over their published interfaces,
each behind one module so it can be replaced.

"""


#: `## Flask 2.3.3` — the head of an entry, and the only structure this
#: file has. Read back so an absent package's text can be carried over.
_ENTRY = re.compile(r"^## (?P<name>\S+)(?: (?P<version>\S+))?$", re.M)


def pins():
    """name -> pinned version, for everything a published image installs."""
    from tests.test_dependency_licences import _pins
    return dict(sorted(_pins().items()))


def _already_written(text):
    """The file as it stands: lowercased name -> (shown name, version, body).

    Parsed back rather than kept somewhere else, because the file IS the
    record — a sidecar holding the same licence texts would be a second copy
    to keep in step with the first.
    """
    entries, heads = {}, list(_ENTRY.finditer(text))
    for index, head in enumerate(heads):
        end = heads[index + 1].start() if index + 1 < len(heads) else len(text)
        name = head.group("name")
        entries[name.lower()] = (name, head.group("version"),
                                 text[head.end():end].lstrip("\n"))
    return entries


def _licence_text(distribution):
    """The licence as the wheel shipped it, or None.

    A package that ships none is not a problem to solve here: the metadata
    still says which licence it is under, and this file says the wheel
    carried no copy rather than inventing one.
    """
    for path in distribution.files or ():
        name = os.path.basename(str(path)).lower()
        if "dist-info" not in str(path).lower():
            continue
        if not name.startswith(("license", "licence", "copying", "notice")):
            continue
        try:
            # `path.read_text()`, not `distribution.read_text(path)`: the
            # second takes a name relative to the dist-info directory, and
            # every one of these is `<dist-info>/licenses/LICENSE` — which
            # it looks for one directory too high and does not find. It
            # returns None rather than raising, so the first version of
            # this reported that no wheel ships a licence at all.
            return path.read_text()
        except Exception:
            return None
    return None


def _declared(meta):
    """What the package says its licence is, as one line."""
    for key in ("License-Expression", "License"):
        for value in meta.get_all(key) or []:
            if value and len(value.splitlines()) == 1:
                return value.strip()
    classifiers = [c.split("::")[-1].strip()
                   for c in (meta.get_all("Classifier") or [])
                   if c.startswith("License ::")]
    return "; ".join(classifiers) or "see the text below"


def _body(distribution, meta):
    """Everything under the heading, for a package that is installed."""
    home = (meta.get("Home-page")
            or next((url.split(", ", 1)[-1]
                     for url in (meta.get_all("Project-URL") or [])
                     if url.lower().startswith(("homepage", "source",
                                                "repository"))), ""))
    body = [f"- Licence: {_declared(meta)}\n"]
    if home:
        body.append(f"- Home: {home}\n")
    text = _licence_text(distribution)
    if text:
        body.append("\n```\n" + text.strip() + "\n```\n\n")
    else:
        body.append("\nThe wheel ships no licence file; the licence above "
                    "is what its metadata declares.\n\n")
    return "".join(body)


def _on_disk():
    if not os.path.exists(OUTPUT):
        return ""
    with open(OUTPUT, encoding="utf-8") as handle:
        return handle.read()


def render(existing=None):
    kept = _already_written(_on_disk() if existing is None else existing)

    out = [HEADER]
    for name, version in pins().items():
        try:
            distribution = metadata.distribution(name)
        except metadata.PackageNotFoundError:
            distribution = None

        if distribution is not None:
            meta = distribution.metadata
            # The pin decides the version and the wheel decides the spelling
            # of the name. `PyYAML` and `SQLAlchemy` are not how anybody
            # writes them in requirements.txt, and a file that renamed them
            # every other generation would be a diff about nothing.
            out.append(f"## {meta['Name']} {version or distribution.version}\n\n")
            out.append(_body(distribution, meta))
            continue

        shown, written_for, body = kept.get(name, (name, None, ""))
        if body and written_for == version:
            # Absent here, and the entry on disk was written for exactly
            # this version. Carried over, so regenerating on a machine
            # missing one package does not delete what another machine
            # recorded.
            out.append(f"## {shown} {version}\n\n{body}")
            continue
        out.append(f"## {shown} {version or '(no pinned version)'}\n\n"
                   f"- Licence: not recorded here yet\n\n"
                   f"This package is not installed in the environment this "
                   f"was generated from, and the entry on file"
                   f"{' is for ' + written_for if written_for else ' does not exist'}"
                   f". Regenerate where it is installed — the browser image "
                   f"stage installs it.\n\n")
    return "".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the file on disk is not this")
    arguments = parser.parse_args()

    existing = _on_disk()
    written = render(existing)
    if arguments.check:
        if existing == written:
            print(f"{os.path.basename(OUTPUT)} is up to date "
                  f"({len(pins())} packages).")
            return 0
        print(f"{os.path.basename(OUTPUT)} is stale. Run:\n"
              f"    python tools/third_party_notices.py", file=sys.stderr)
        return 1

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write(written)
    print(f"Wrote {OUTPUT} ({len(pins())} packages).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
