#!/usr/bin/env python3
"""
Write THIRD-PARTY-NOTICES.md from what is actually installed.

    python tools/third_party_notices.py            # write it
    python tools/third_party_notices.py --check     # exit 1 if it is stale

A release ships other people's code, and most of their licences ask for the
notice to travel with it. Keeping that list by hand means keeping it wrong:
a dependency is added in one line and the notice is somebody else's problem
three months later.

Read from installed metadata rather than from requirements.txt alone, for
the reason `tests/test_dependency_licences.py` reads it too — the versions
that matter are the ones in the image, and the browser image installs
Playwright in its own stage. The set of names comes from that module, so
the notices and the licence rule cannot disagree about what ships.

No new dependency. `importlib.metadata` is the standard library, and the
licence text is whatever the wheel put in its `dist-info`.
"""

import argparse
import importlib.metadata as metadata
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

OUTPUT = os.path.join(ROOT, "THIRD-PARTY-NOTICES.md")

HEADER = """# Third-party notices

WDash is MIT licensed. It ships other people's work, and this file is that
work: every runtime dependency of the published images, the version pinned,
the licence it is under, and the licence text where the package carries one.

Generated by `tools/third_party_notices.py` from installed metadata, which
is what `requirements.txt` pins and what the Dockerfile installs — not a
list kept by hand. `tests/test_release_files.py` fails if it is stale, and
`RELEASING.md` names the command.

Nothing here is proprietary or source-available; that rule is enforced
separately, by `tests/test_dependency_licences.py`. Two are LGPL v3 —
`ldap3` and `psycopg` — used as libraries over their published interfaces,
each behind one module so it can be replaced.

"""


def names():
    """Everything installed that ends up in a published image."""
    from tests.test_dependency_licences import _requirements
    return sorted(_requirements())


def _licence_text(distribution):
    """The licence as the wheel shipped it, or None.

    A package that ships none is not a problem to solve here: the metadata
    still says which licence it is under, and this file says the wheel
    carried no copy rather than inventing one.
    """
    for path in distribution.files or ():
        name = os.path.basename(str(path)).lower()
        if "dist-info" not in str(path).lower():
            continue
        if not name.startswith(("license", "licence", "copying", "notice")):
            continue
        try:
            # `path.read_text()`, not `distribution.read_text(path)`: the
            # second takes a name relative to the dist-info directory, and
            # every one of these is `<dist-info>/licenses/LICENSE` — which
            # it looks for one directory too high and does not find. It
            # returns None rather than raising, so the first version of
            # this reported that no wheel ships a licence at all.
            return path.read_text()
        except Exception:
            return None
    return None


def _declared(meta):
    """What the package says its licence is, as one line."""
    for key in ("License-Expression", "License"):
        for value in meta.get_all(key) or []:
            if value and len(value.splitlines()) == 1:
                return value.strip()
    classifiers = [c.split("::")[-1].strip()
                   for c in (meta.get_all("Classifier") or [])
                   if c.startswith("License ::")]
    return "; ".join(classifiers) or "see the text below"


def render():
    out = [HEADER]
    for name in names():
        try:
            distribution = metadata.distribution(name)
        except metadata.PackageNotFoundError:
            out.append(f"## {name}\n\nNot installed in the environment this "
                       f"was generated from.\n\n")
            continue
        meta = distribution.metadata
        home = (meta.get("Home-page")
                or next((url.split(", ", 1)[-1]
                         for url in (meta.get_all("Project-URL") or [])
                         if url.lower().startswith(("homepage", "source",
                                                    "repository"))), ""))
        out.append(f"## {meta['Name']} {distribution.version}\n\n")
        out.append(f"- Licence: {_declared(meta)}\n")
        if home:
            out.append(f"- Home: {home}\n")
        text = _licence_text(distribution)
        if text:
            out.append("\n```\n" + text.strip() + "\n```\n\n")
        else:
            out.append("\nThe wheel ships no licence file; the licence above "
                       "is what its metadata declares.\n\n")
    return "".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the file on disk is not this")
    arguments = parser.parse_args()

    written = render()
    if arguments.check:
        existing = (open(OUTPUT, encoding="utf-8").read()
                    if os.path.exists(OUTPUT) else "")
        if existing == written:
            print(f"{os.path.basename(OUTPUT)} is up to date "
                  f"({len(names())} packages).")
            return 0
        print(f"{os.path.basename(OUTPUT)} is stale. Run:\n"
              f"    python tools/third_party_notices.py", file=sys.stderr)
        return 1

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write(written)
    print(f"Wrote {OUTPUT} ({len(names())} packages).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
